### PR TITLE
SSH is also FTP

### PR DESCRIPTION
**Pull request by mkz212**
This option enable / disable both: SSH and FTP.

### CODE REVIEW

**Comment by XECDesign** [comment]
Assuming you mean SFTP, then it's a completly different protocol and is a feature of SSH. I think SFTP is already implied when SSH is mentioned.

If we start adding every feature of SSH to this menu entry, it will take up the whole screen. Is there a reason it's important to mention this one in particular?

**Comment by mkz212** [comment]
> Assuming you mean SFTP, then it's a completly different protocol and is a feature of SSH. I think SFTP is already implied when SSH is mentioned.
> 
> If we start adding every feature of SSH to this menu entry, it will take up the whole screen. Is there a reason it's important to mention this one in particular?

No. We don't understand each other. I mean FTP (and FTPS (SSL)), i.e. access to files. I know it sounds strange, but this option enable and deactivates both: SSH (command line) and FTP / FTPS (file browser) at the same time. Seriously. When this option is disabled, you cannot connect via FTP / FTPS.

**Comment by XECDesign** [comment]
Oh okay, that's... interesting. Could you please elaborate? How do I reproduce this behaviour so I can investigate? Because it sounds more like a bug than a feature.

Are you connecting to a remote ftp server or are you running one? What client/server software is being used?

**Comment by mkz212** [comment]
@XECDesign 

Forgive me, my mistake. However, I checked and it is SFTP. I corrected the PR. I think it should be known that this also activates file transfer.

I'm using Homebridge on Raspberry Pi. Connecting via Cyberduck (SFTP, port 22, Raspberry IP as server, user pi).

**Comment by XECDesign** [comment]
Then I go back to my first response. They're not separate services. SFTP, along with many other features, is a part of SSH. Why does it need too be mentioned separately? It's possible to separate them and force one without the other, but that's a rare configuration.

**Comment by mkz212** [comment]
The vast majority thinks that this is only to enable the command line and have no idea that there is such a thing as SSH FTP. That's why they install some additional plugins for FTP without knowing that they have a built-in option.

**Comment by XECDesign** [comment]
I can't speak for the vast majority, but I'm not seeing evidence of that. There has been no mention of FTP or SFTP on any of the github issues in 12 years or so and I haven't seen any confusion about it before. I'm inclined to leave it as is, unless there's is evidence of a significant number of confused users.

**Pull request closed without merging**
