### PR TITLE
Allow Raspberry Pi 4 To Be Overclocked In The Menu

### PR DESCRIPTION
**Pull request by Void-Frost**
Hello,

All I did was modify a few if/else statements, and add some if/else statements.

Configs tested and working on my Raspberry Pi 4 B+ 4GB.

### CODE REVIEW

**Comment by XECDesign** [comment]
IIRC, the reason overclocking through raspi-config was left out is that there's not as much headroom for it. On the early models, we provided relatively safe overclock values. On the newer models, it's up to the user to determine what their silicon can handle.

@spl237 does that sound about right?

**Comment by spl237** [comment]
> @spl237 does that sound about right?

Yes, exactly. It was a deliberate decision to not offer overclocking on newer platforms, and so it's not included in raspi-config or the GUI.

**Comment by Void-Frost** [comment]
Out of curiosity: what's the harm of having options even if they don't necessarily work on every pi 4? It's easy enough to revert OC imo (hold shift on boot, that is).

**Comment by XECDesign** [comment]
Originally, the "hold shift" message was quite obvious. Nowadays with the splash screen and general noise of boot message spam, it's very easy to not know that that's something you can do. raspi-config is intended for beginners, so making it easy to shoot yourself in the foot is not what it's for.

**Comment by Void-Frost** [comment]
Correct me if I'm wrong here, isn't hold shift on boot also mentioned in raspi-config whenever you hit the overclock menu? Could've sworn it was.

**Comment by spl237** [comment]
Our official position is that we do not offer overclocking on Pi 4 - it's not needed for the vast majority of users, as Pi 4 already runs sufficiently quickly for most people's requirements, and overclocking is not recommended without additional cooling. On Pi 1, the speed boost from overclocking was more useful, and the cooling requirements less severe. Thank you for your work on the PR, but we will not be adding this functionality to raspi-config.

**Comment by Void-Frost** [comment]
Understood, thanks for the consideration.

**Pull request closed without merging**
