### PR TITLE
Fix default gpu_mem for boards with >=1GB RAM

### LINKED ISSUE #122: Default gpu_mem is now 76MB, not 64MB
raspi-config thinks the default setting for `gpu_mem` is 64MB - it's not. If there is no `gpu_mem` directive specified in `config.txt`, the firmware now defaults to allocating 76MB to the GPU. `raspi-config` should be modified accordingly.

### PR DESCRIPTION
**Pull request by andrum99**
Fixes #122

### CODE REVIEW

**Comment by andrum99** [comment]
Also works correctly if the user uses total_mem to bring total available memory down below 1024. (Which is how I tested it).

**Comment by andrum99** [comment]
Hmm, OK. After some further experimentation with total_mem on a Pi 4B, it seems the firmware actually does this:

- for `total_mem` <= 1008MB, `gpu_mem` defaults to 64MB
- for `total_mem` > 1008MB `gpu_mem` defaults to 76MB

I've fixed up the PR to match this behaviour.

(`rc_gui` already does the right thing - it just calls `vcgencmd get_mem gpu` in the case where there is no `gpu_mem` specified in `config.txt`).

**Comment by andrum99** [comment]
Note that with this PR, if `raspi-config` cannot calculate the total amount of memory in the system (sum of `vcgencmd get_mem arm` and `vcgencmd get_mem gpu`) then it will pick 76MB as the default. I'm not entirely sure if 76 or 64MB is best in that case, but since there's more Pis with > 1008MB RAM that's probably the one to go for. On the other hand, it's perhaps more likely that `get_total_mem()`, and its equivalent in `raspi-config`, will fail on Pis with <= 1008MB RAM.

**Comment by XECDesign** [comment]
Maybe using `vcgencmd get_mem gpu` instead would help avoid this kind of thing in the future altogether?

**Pull request closed without merging**
