### PR TITLE
add non-interactive mode for do_gldriver

### PR DESCRIPTION
**Pull request by heeplr**

### CODE REVIEW

**Comment by XECDesign** [comment]
The nonint options are generally for use with pipanel, I don't know whether the expectation is that all of raspi-config options should be available in nonint mode.

@spl237, I think this is your part of raspi-config. Would you like to test/merge this or not?

**Comment by spl237** [comment]
It's not an option which ought to be exposed to the GUI, so this change is just unnecessary risk from my POV.

**Comment by heeplr** [comment]
I thought it was just forgotten since looking at the code I noticed that every do_* function handles the INTERACTIVE environment variable consistently (except do_passwd, do_update, do_finish and do_*_menu for obvious reasons).

To me it looks like an inconcistency. I also can't see any risk imposed and would love to learn more about that.

**Comment by spl237** [comment]
> I thought it was just forgotten since looking at the code I noticed that every do_* function handles the INTERACTIVE environment variable consistently (except do_passwd, do_update, do_finish and do_*_menu for obvious reasons).

The non-interactive versions of functions are called by the rc_gui shell program. This function, like most of those in the advanced menu, is not called from that program, so doesn't need a non-interactive version.

> I also can't see any risk imposed and would love to learn more about that.

Any change to code which currently works as intended introduces risk. I have on several occasions accepted PRs which have looked ok at first glance and have subsequently turned out to introduce subtle bugs. As a result, I don't accept unnecessary changes, just in case.

**Comment by XECDesign** [comment]
+1

Sometimes reviewing a change carefully takes more time that making the change yourself. More often than not, any time I've merged something thinking "this looks harmless enough", it has come back to bite me.

**Comment by heeplr** [comment]
To avoid regression bugs in complex bash projects a test framework like [bats](https://github.com/bats-core/bats-core/) helps a lot.
Also, static code analysis with something like [shellcheck](https://www.shellcheck.net/) could find a lot of hidden bugs that play out nicely until some point. Then CI could reduce headaches with PRs aswell.

**Pull request closed without merging**
