### PR TITLE
init: Do not disable 'ondemand' governor on shift

### PR DESCRIPTION
**Pull request by roliver-rpi**

### CODE REVIEW

**Comment by roliver-rpi** [comment]
@XECDesign and @spl237 , I would appreciate any input you might have.

Cheers,
Richard

**Comment by spl237** [comment]
Not an area I know anything about, so fine with me unless Serge has any concerns?

**Comment by XECDesign** [comment]
Nope, I'm glad to see this go.

Doesn't `etc/default/cpu_governor` also need to be in maintscript?

Also, wouldn't it mean people will be stuck with powersave unless they upgrade the kernel to a version that's not in apt yet? If that's the case, then I don't think we can merge it until that kernel has been out for a while.

**Comment by roliver-rpi** [comment]
`cpu_governor` is less critical as it won't cause any ill-effects if it's left on-disk; I'm happy to actively remove it though if we think that's for the best? It might be possible to get that one with the 'remove-on-upgrade' flag in conffiles.

In terms of being stuck on powersave, would get get away with marking this package as 'Breaks' or 'Conflicts' with older kernel versions such that the new version of this package doesn't get selected until the kernel version moves on?

**Comment by XECDesign** [comment]
> In terms of being stuck on powersave, would get get away with marking this package as 'Breaks' or 'Conflicts' with older kernel versions such that the new version of this package doesn't get selected until the kernel version moves on?

I think some set of users will see that there's a package update being held back and try to install it anyway, which will result in the kernel getting deleted. I think it's best to just wait until the new kernel has been out for a few months and then make this change.

**Comment by timg236** [comment]
Is it still worth changing it so that it's no-longer and init service and dropping the SHIFT key behavior? There still needs to be something that reads /etc/default and picks the on-demand parameters but there's no need for this to be interactive

**Comment by XECDesign** [comment]
> Is it still worth changing it so that it's no-longer and init service and dropping the SHIFT key behavior? There still needs to be something that reads /etc/default and picks the on-demand parameters but there's no need for this to be interactive

Yeah, good point.

**Comment by roliver-rpi** [comment]
> Is it still worth changing it so that it's no-longer and init service and dropping the SHIFT key behavior? There still needs to be something that reads /etc/default and picks the on-demand parameters but there's no need for this to be interactive

I'll put a change together that implements this.

**Comment by XECDesign** [comment]
A quick and easy step might be to just remove the use of thd and timeout and just default to the behaviour that happens when shift is not pressed.

**Comment by roliver-rpi** [comment]
I've forced-pushed my `no_shift` branch; this removes the need for a separate service all together as a combination of udev/tmpfiles rules are used to select/configure the ondemand governor.

**Pull request merged**
