### PR TITLE
Added first boot resize asking dialog

### PR DESCRIPTION
**Pull request by Jujan**
I was browsing forum when I got around this thread: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=164500
There was one engineer stating "The script can't be interactive".
So I made it interactive, asking user for resizing root partition at first initial startup.
You know, never say never.
Please, tell me your opinions. Code cleanups or potential bugfixes welcomed. Thanks.

### CODE REVIEW

**Comment by XECDesign** [comment]
The "can't be" wasn't meant to be taken as a challenge or to imply that it's difficult or impossible. In hindsight, that should've probably been a "shouldn't be". Is there a good reason for the patch given the reasons not to do it in that thread?

**Comment by Jujan** [comment]
Yes. I noticed that when I take out init from cmdline.txt to prevent resizing and reboot the boot related messages list is unusually short (it fills my screen without scrolling), but when I boot with resize script it shows about two time more entries (it scrolls the messages and it finishes at lenght of about two screens). I suspect that the resize script somehow activates systemd or other system part. Specifically: Boot without the resize script does not wait for dhcpd when no connection set. Boot with the script does wait for dhcpd when no connection set. (cable disconnected and no entry in wpa_supplicant.conf).

**Comment by XECDesign** [comment]
That sounds like a separate issue. Would you be able to post the logs? In my testing, it times out waiting for dhcpcd in both cases, as expected.

**Comment by Jujan** [comment]
Uh, Ha. Sorry for confusing you, the dhcpd is not showing without first reboot and after that works as expected. Here are the journalctl logs. If not enough I can provide video evidence of what I mean.
[withscript.txt](https://github.com/RPi-Distro/raspi-config/files/1221968/withscript.txt)
[noscript.txt](https://github.com/RPi-Distro/raspi-config/files/1221969/noscript.txt)

**Comment by XECDesign** [comment]
I don't see any major difference between those two logs. dhcpcd behaves the same in both cases. I see that you have 'quiet' in one cmdline.txt, but not the other, which would account for the difference you're describing. You'd see less messages with 'quiet' on the screen, but it's still behaving the same way underneath.

**Comment by Jujan** [comment]
Oh! You are right! I did not noticed that. I thought that it would be useful to let user choose at startup if he likes to resize the partition. Everything other seems fine and work as expected. Now it is up to you if you thought it same, still awesome my first pull request on GitHub. See you later.

**Comment by XECDesign** [comment]
Thanks for confirming.

**Pull request closed without merging**
