### PR TITLE
non-interactive mode for overlay fs

### PR DESCRIPTION
**Pull request by snblackout**

### CODE REVIEW

**Comment by guillaumezin** [comment]
Not sure it's necessary, you can call functions of raspi-config sourcing it with "nonint" arg (I redid this script https://github.com/ghollingworth/overlayfs/blob/master/overctl using raspi-config as library):
```
#!/bin/bash

print_usage() {
	cat <<-TEXT
		Usage: ${0##*/} [-h|-r|-s|-t|-w]
		   -h, --help     This message
		   -r, --ro       Set read-only root with overlay fs
		   -s, --status   Show current state
		   -t, --toggle   Toggle between -r and -w
		   -w, --rw       Set read-write root
	TEXT
}

main() {
	# Check whether user requests help
	[ "$1" = "--help" -o "$1" = "-h" ] && { print_usage; exit 0;}

	# Process arg (if any)
	case "$1" in
		--ro|-r)	action=RO
				;;
		--rw|-w)	action=RW
				;;
		--status|-s)	action=status
				;;
		--toggle|-t)	action=toggle
				;;
		*)		print_usage
				exit 1
				;;
	esac

	# Check which CMDLINE is in use, this doubles as a sanity check
	if get_overlay_conf; then
		state=RO
	else
		state=RW
	fi

	if get_bootro_now; then
		BOOTRO=yes
	else
		BOOTRO=no
	fi

	check_permission() {
		# Check that we are running as root
		[ $(id -u) -eq 0 ] || { echo "ERROR: requires root privileges" >&2; exit 1; }
		return 0
	}

	# Take action
	if [ "$action" = "status" ]; then
		if get_overlay_now; then
			echo -n "/ is currently mounted RO" >&2
		else
			echo -n "/ is currently mounted RW" >&2
		fi

		echo " and will be mounted $state on next boot" >&2
		exit 0
	elif [ "$action" = "$state" ]; then
		echo "/ is already set to be mounted $state on next boot" >&2
		exit 1
	elif [ "$state" = "RO" ]; then
		check_permission
		disable_overlayfs
		newstate=RW
	elif [ "$state" = "RW" ]; then
		check_permission
		enable_overlayfs
		newstate=RO
	fi

	echo "/ will be mounted $newstate on next boot" >&2

	# The End
	exit 0
}

arg1="$1"

trap 'main "$arg1"' EXIT

source raspi-config nonint
```

**Comment by mangelozzi** [comment]
> Not sure it's necessary, you can call functions of raspi-config sourcing it with "nonint" arg (I redid this script https://github.com/ghollingworth/overlayfs/blob/master/overctl using raspi-config as library):

If you are a none bash guru, I would say it's necessary. I would very much welcome this PR.
How does one use the "nonint" arg? Where is it documented, how is someone supposed to know of it/figure it out? Cheers!

**Comment by bensonrodney** [comment]
You can do this (I have been):
`sudo raspi-config nonint do_overlayfs 0`
(0 for enable, 1 for disable)

**Comment by snblackout** [comment]
> You can do this (I have been): `sudo raspi-config nonint do_overlayfs 0` (0 for enable, 1 for disable)

Very interesting.  I had no idea you could do this that way, why I made the PR.  Can this also be done in the same manner for write-protecting the boot partition?

**Comment by bensonrodney** [comment]
> > You can do this (I have been): `sudo raspi-config nonint do_overlayfs 0` (0 for enable, 1 for disable)
> 
> Very interesting. I had no idea you could do this that way, why I made the PR. Can this also be done in the same manner for write-protecting the boot partition?

See:
https://github.com/RPi-Distro/raspi-config/blob/master/raspi-config#L2807

The link above is basically the entry point for the raspi-config script and further down you can see the `nonint` case just sets INTERACTIVE to false and then runs what ever arguments after `sudo raspi-config nonint` you've added. Basically you're calling functions in this script, most of the ones you want are the `do_<config_item>` for any of the configuration items but you need to know what parameters are valid and what they mean.

As for write protecting the boot partition, not sure if there's a setup for that in raspi-config as it is but also not sure if you even need it. Typically things aren't writing to the boot partition, I'm guessing?

**Comment by XECDesign** [comment]
Looks like this one has been addressed. Thank you.

**Comment by mangelozzi** [comment]
> Looks like this one has been addressed. Thank you.

Well I would say it is great that it supports it, but only the people who work on the script know about it. Could it be added to the help?

**Comment by snblackout** [comment]
> > Looks like this one has been addressed. Thank you.
> 
> Well I would say it is great that it supports it, but only the people who work on the script know about it. Could it be added to the help?

Agreed.  This needs to be documented somewhere for sure.

**Comment by XECDesign** [comment]
I've briefly addressed that here https://github.com/RPi-Distro/raspi-config/issues/182#issuecomment-1055573335

But yes, I see your point when it comes to this particular option and in general the `nonint` commands are quite useful (if you know about them).

Being honest, maintaining documentation for an ever-changing tool like raspi-config (which is meant to be self-explanatory), is quite low on the list of valuable ways to spend time. It's not something I'd volunteer myself or anybody else for, so I'm conflicted about this. Yes, it's useful but is it THAT useful? Then if we accept a PR, it's likely to be out of date or wrong in some way a little later down the line.

**Comment by snblackout** [comment]
> It's not something I'd volunteer myself or anybody else for, so I'm conflicted about this.

It's a tough one.  I'd be happy if just a tech blogger would take this up themselves to do an article at least (I am not one).  Having something out there that is crawled by Google for a "non-interactive raspi-config tutorial" would be beneficial.  If the article goes out of date, hopefully someone will pick up and create a new one or update it.

So maybe if anyone in this thread knows of someone that may have an interest to make an article about it, shoot it their way. :)

**Comment by XECDesign** [comment]
@aallan, I should ping you, since documentation is your area.

**Comment by aallan** [comment]
> @aallan, I should ping you, since documentation is your area.

Okay, this isn't something I knew was possible. But, yes, sounds like it should be in the documentation somewhere. I'll add an issue to the [raspberrypi/documentation](https://github.com/raspberrypi/documentation) repo so that this doesn't get lost.

**Comment by mangelozzi** [comment]
> You can do this (I have been): `sudo raspi-config nonint do_overlayfs 0` (0 for enable, 1 for disable)

Correct me if I am wrong, but say the boot and filesystem both have overlayfs enabled, then if one does:
`sudo raspi-config nonint do_overlayfs 1`,
It pops up with a dialogue saying: "The boot partition is currently read-only. This cannot be changed while an overlay file system is enabled."
Maybe the `nonint` is not handling the follow up message?

**Pull request closed without merging**
