### PR TITLE
Detection of P3 and add command lines for timezone, hostname, overcloc…

### PR DESCRIPTION
**Pull request by MarkusLange**
…k and memory-split

Add detection for the RPi 3 (3 Model B, CM3, CM3 Lite)
Add functions for command line:
--memory-split= usually 16 32 64 ... MB
--timezone= set with Zone/Local eg. Europe/Berlin
--hostname= just set the name
--overclock= set with the options known from the whiptail menu

### CODE REVIEW

**Comment by MarkusLange** [comment]
Oh I see alecthegeek has also try to add this there https://github.com/asb/raspi-config/pull/23

**Comment by XECDesign** [comment]
I think we've settled on the `noint` approach:
https://github.com/raspberrypi-ui/rc_gui/blob/master/src/rc_gui.c#L24

What is the `is_pithree` function for?

**Comment by XECDesign** [comment]
No response

**Comment by MarkusLange** [comment]
Sorry was busy, is pithree is to identify if it is an Pi 3 you are working on

**Comment by XECDesign** [comment]
Right, but that functionality is not used by Raspbian or within raspi-config (yet). It seems strange to add a function that's never called.

**Pull request closed without merging**
